version: '3.8'

services:
  app:
    image: node:20-alpine
    working_dir: /app
    expose:
      - "3000"
    volumes:
      - ./:/app
    command: sh -c "npm install && npm start"
    restart: unless-stopped

