version: '3.8'

services:
  frontend:
    image: nginx:alpine
    expose:
      - "80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: python:3.11-slim
    working_dir: /app
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    command: sh -c "pip install -r requirements.txt && python app.py"
    restart: unless-stopped

