version: '3.8'

services:
  api:
    image: python:3.11-slim
    working_dir: /app
    expose:
      - "8000"
    volumes:
      - ./:/app
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped

